name: E2E Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 5s
          --health-timeout 30s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start app with Docker Compose
        run: docker-compose -f docker-compose.yml up -d --build
        working-directory: apps/server

      - name: Run tests
        run: docker exec app-test yarn test:e2e

      - name: Stop containers
        run: docker-compose -f docker-compose.yml down
        working-directory: apps/server
